# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import expense_trackapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_trackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=expense_trackapp.models.get_current_date),
        ),
    ]
